name: check compatibility specs

on:
  workflow_dispatch:
  pull_request: []

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run Validation
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-setuptools wget
        sudo pip3 install -r .github/requirements.txt
        python3 .github/validate.py .

